services:
  # The frontend static file server (Vite build)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - PORT=3000

  # The Python microservice (Calculations)
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    # Internal port 8888, exposed only to the network
    volumes:
      - ./data:/app/data
      - ./python-server/src/parser-data:/app/parser-data

  # The Go microservice (API / Routes)
  parser-ms:
    build:
      dockerfile: cmd/parser-ms/Dockerfile
    ports:
      # Configured as such due to deployment environment reasons
      - "127.0.0.1:5000:8080"
    environment:
      - CORS_ALLOW_ORIGIN=*
      - PYTHON_SERVICE_HOST=python-server
      - PYTHON_SERVICE_PORT=8888
    volumes:
      - ./data:/app/data
